import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CheckCircle, FileCheck, Download } from "lucide-react";

const pendingSignOffs = [
  {
    id: 1,
    reportType: "Daily Sales Report",
    date: "2024-01-15",
    generatedBy: "System",
    status: "pending",
  },
  {
    id: 2,
    reportType: "Stock Reconciliation",
    date: "2024-01-15",
    generatedBy: "Manager",
    status: "pending",
  },
  {
    id: 3,
    reportType: "Shift Summary",
    date: "2024-01-14",
    generatedBy: "Manager",
    status: "pending",
  },
];

export const DigitalSignOffCard = () => {
  return (
    <Card className="p-6">
      <div className="mb-6">
        <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
          <FileCheck className="w-5 h-5 text-primary" />
          Digital Sign-Off
        </h3>
        <p className="text-sm text-muted-foreground mt-1">Reports awaiting verification</p>
      </div>

      <div className="space-y-3">
        {pendingSignOffs.map((report) => (
          <div
            key={report.id}
            className="p-4 rounded-lg border border-border bg-card hover:bg-accent/50 transition-colors"
          >
            <div className="flex items-start justify-between mb-3">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <p className="font-semibold text-foreground">{report.reportType}</p>
                  <Badge variant="secondary" className="bg-warning/20 text-warning">
                    Pending
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {report.date} • Generated by {report.generatedBy}
                </p>
              </div>
            </div>

            <div className="flex gap-2 mt-3 pt-3 border-t border-border">
              <Button variant="outline" size="sm" className="flex-1">
                <Download className="w-4 h-4 mr-1" />
                Preview
              </Button>
              <Button variant="default" size="sm" className="flex-1 bg-success hover:bg-success/90">
                <CheckCircle className="w-4 h-4 mr-1" />
                Sign Off
              </Button>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 p-4 rounded-lg bg-primary/10 border border-primary/30">
        <h4 className="font-semibold text-foreground mb-2">Digital Signature</h4>
        <p className="text-sm text-muted-foreground mb-3">
          Your digital signature will be recorded with timestamp and IP address for audit compliance.
        </p>
        <div className="flex items-center gap-2 text-sm">
          <CheckCircle className="w-4 h-4 text-success" />
          <span className="text-foreground">Audit trail enabled</span>
        </div>
      </div>

      <Button variant="outline" className="w-full mt-4">
        Export Audit Report
      </Button>
    </Card>
  );
};
